### PR TITLE
Process filter string once instead of per test

### LINKED ISSUE #3614: gtest_filter slow
**Describe the bug**

Running va-api's 17,415 gtest tests is slow (~25 minutes on Chrome OS's "grunt" boards), so I'm parallelizing it by sharding to multiple threads running multiple tests per gtest process invocation (https://gitlab.freedesktop.org/anholt/deqp-runner/-/merge_requests/24).  By specifying the tests to run on each shard as a `gtest_filter` separated by ':', we're now spending more CPU in `FilterMatchesTest()` than in the actual tests.  On my desktop, perf says I've got 35% of my CPU spent under main() of my unit tests, and 30% under `FilterMatchesTest()`

If at startup googletest could parse the filter list and toss the non-glob-containing filters into a set, leaving just a vec of glob-containing filters to go through `PatternMatchesString()`, that should be make the filter cheap for the case of "lots of names of specific tests to run"

**Steps to reproduce the bug**
```
git clone from that deqp-runner branch
cargo install --path .

# replace test_va_api here with a handy gtest binary with 17k tests in it
perf record -g gtest-runner run --gtest ~/test_va_api --output <output_dir>
perf report -g
```

**Does the bug persist in the most recent commit?**

Tested on fd873f6d7d22e231a083a7fc570f95961c36e85c, hoping that might help, but no luck (I'm not using globs, so the fixes to globbing didn't do much).

**What operating system and version are you using?**

debian unstable

**What compiler and version are you using?**

`gcc version 11.2.0 (Debian 11.2.0-9) `

**What build system are you using?**

meson "debugoptimized" buildtype (-O2 but with assertions)

### PR DESCRIPTION
**Pull request by IYP-Programer-Yeah**
Fixes #3614

Improve filter performance by removing extra string processing that is performed for each test that can rather  be performed only once per execution .

### CODE REVIEW

**Comment by IYP-Programer-Yeah** [comment]
Hey, just wanted to ping this PR for review. @dinord

**Comment by IYP-Programer-Yeah** [comment]
@derekmauro @dinord wanted to ping so that this merge request doesn't go stale.

**Comment by dinord** [comment]
Apologies for the delay, we'll begin reviewing this shortly.

**Comment by IYP-Programer-Yeah** [comment]
Pinging again. Honestly this is extremely odd that a merge request takes 5 weeks.

File: googletest/src/gtest.cc [hunk 1]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
+  }
+};
+
+class PositiveAndNegativeFilter {
+  Filter positive_filter_;
+  Filter negative_filter_;
+
+  static std::pair<std::string, std::string>
+  BreakIntoPositiveAndNegativeFilters(const std::string& filter) {
+    const auto dash_pos = filter.find('-');
```
Comment (dinord) [inline googletest/src/gtest.cc:763]: Can we reuse the `SplitString` function defined in this file?
https://github.com/google/googletest/blob/3e0e32ba300ce8afe695ad3ba7e81b21b7cf237a/googletest/src/gtest.cc#L1156

File: googletest/src/gtest.cc [hunk 2]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
+      return PatternMatchesString(name, pattern.c_str(),
+                                  pattern.c_str() + pattern.size());
+    };
+    return std::any_of(patterns_.begin(), patterns_.end(),
+                       pattern_matches_name);
+  }
+};
+
+class PositiveAndNegativeFilter {
+  Filter positive_filter_;
```
Comment (dinord) [inline googletest/src/gtest.cc:758]: Could we put this in a private section at the end of the class definition?
https://google.github.io/styleguide/cppguide.html#Class_Format

File: googletest/src/gtest.cc [hunk 3]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
+      return {filter, {}};  // Whole string is a positive filter
+    } else {
+      return {dash_pos ? filter.substr(0, dash_pos) : kUniversalFilter,
+              filter.substr(dash_pos + 1)};
     }
-    pattern = next_sep + 1;
   }
-  return true;
-}
+  PositiveAndNegativeFilter(
```
Comment (dinord) [inline googletest/src/gtest.cc:771]: Can we inline everything (including `BreakIntoPositiveAndNegativeFilters`) into a single constructor to improve readability by avoiding some indirection?

I don't think we care that much about the difference in performance between initializer lists vs. `std::move`ing the members in the body of the constructor. We won't be constructing filter instances that often anyway.

**Review by dinord — COMMENTED** [review]
Neat.

File: googletest/src/gtest.cc [hunk 4]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
-  while (true) {
-    // Find the bounds of this pattern.
-    const char* const next_sep = strchr(pattern, ':');
-    const char* const pattern_end =
-        next_sep != nullptr ? next_sep : pattern + strlen(pattern);
-
-    // Check if this pattern matches name_str.
-    if (PatternMatchesString(name_str, pattern, pattern_end)) {
-      return true;
+class Filter {
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

File: googletest/src/gtest.cc [hunk 5]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
+  std::vector<std::string> patterns_;
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

File: googletest/src/gtest.cc [hunk 6]
```diff
@@ -723,60 +723,91 @@ static bool PatternMatchesString(const std::string& name_str,
...
+
+ public:
+  // Constructs a filter form a string of patterns separated by `:`.
+  explicit Filter(const std::string& filter) {
+    if (filter.empty()) return;
+
+    auto pattern_start = filter.begin();
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

File: googletest/src/gtest.cc (hunk 1 above)
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

File: googletest/src/gtest.cc (hunk 2 above)
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

File: googletest/src/gtest.cc (hunk 3 above)
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: resolved.

**Comment by IYP-Programer-Yeah** [comment]
@dinord requested changes are applied.

File: googletest/src/gtest-internal-inl.h [hunk 7]
```diff
@@ -390,10 +390,6 @@ class GTEST_API_ UnitTestOptions {
   // This function is useful as an __except condition.
   static int GTestShouldProcessSEH(DWORD exception_code);
 #endif  // GTEST_OS_WINDOWS
-
-  // Returns true if "name" matches the ':' separated list of glob-style
-  // filters in "filter".
-  static bool MatchesFilter(const std::string& name, const char* filter);
```
Comment (dinord) [inline googletest/src/gtest-internal-inl.h:396]: Unfortunately, it turns out we have some internal code (i.e. not published to GitHub) that uses this static method.
Instead of deleting it, could we reimplement it using the new APIs?

**Comment by IYP-Programer-Yeah** [comment]
@dinord The main branch is failing, and I do not think the failure in the CI is on my part. Also I have applied the requested changes.

**Comment by IYP-Programer-Yeah** [comment]
Wanted to ping again.

**Comment by IYP-Programer-Yeah** [comment]
Is any one actually reviewing this code?

**Comment by IYP-Programer-Yeah** [comment]
@derekmauro @dinord I found it disturbing that a merge request can take 2 months to be reviewed. What is going on? I see other merge requests are being merged. Is there some specific issue with this merge request?

**Comment by IYP-Programer-Yeah** [comment]
Ah ok, it would be nice to provide some feed back. Since I try to actually be helpful and proceed with requested changes as early as possible. Thanks for the response.

File: googletest/src/gtest.cc [hunk 8]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
+  // negative filter. In case only a negative filter is provided the positive
+  // filter will be assumed "*".
+  // A filter is a list of patterns separated by ':'.
+  explicit PositiveAndNegativeUnitTestFilter(const std::string& filter) {
+    std::vector<std::string> positive_and_negative_filters;
+
+    SplitString(filter, '-', &positive_and_negative_filters);
+    const auto& positive_filter = positive_and_negative_filters.front();
+
+    if (positive_and_negative_filters.size() > 1) {
```
Comment (dinord) [inline googletest/src/gtest.cc:766]: Unfortunately, the original API did not do any validation here -- instead, it just split on the first `-` and ignored others. This would change it to split on all `-` and only consider the first and the last segments if there were more than 2.

Even though it's undefined behavior, I'd retain the original to avoid breaking [inevitable](https://www.hyrumslaw.com/) dependents for now, e.g. by concatenating everything past the first element into the negative filter.
Since we're here, please add a comment like `// TODO: Fail on multiple '-' characters`.

File: googletest/src/gtest.cc [hunk 9]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
-    // Find the bounds of this pattern.
-    const char* const next_sep = strchr(pattern, ':');
-    const char* const pattern_end =
-        next_sep != nullptr ? next_sep : pattern + strlen(pattern);
-
-    // Check if this pattern matches name_str.
-    if (PatternMatchesString(name_str, pattern, pattern_end)) {
-      return true;
-    }
+namespace {
```
Comment (dinord) [inline googletest/src/gtest.cc:726]: nit: Please insert an empty line below this one for consistency with the rest of the file.

**Review by dinord — COMMENTED** [review]
I released a bunch of internal test cases for the matching logic in https://github.com/google/googletest/commit/97a467571a0f615a4d96e79e4399c43221ca1232.
Make sure to rebase and run against them.

**Comment by IYP-Programer-Yeah** [comment]
Thanks for the review will read soon and apply changes accordingly.

File: googletest/src/gtest.cc [hunk 10]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
+    SplitString(filter, '-', &positive_and_negative_filters);
+    const auto& positive_filter = positive_and_negative_filters.front();
+
+    if (positive_and_negative_filters.size() > 1) {
+      positive_filter_ = UnitTestFilter{
+          positive_filter.size() ? positive_filter : kUniversalFilter};
+      negative_filter_ = UnitTestFilter{positive_and_negative_filters.back()};
+    } else {
+      // In case positive filter is empty
+      // we do not use kUniversalFilter by design
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:772]: This is what the old code did, and changing this behavior causes errors in tests.

File: googletest/src/gtest.cc [hunk 11]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
+
+    SplitString(filter, '-', &positive_and_negative_filters);
+    const auto& positive_filter = positive_and_negative_filters.front();
+
+    if (positive_and_negative_filters.size() > 1) {
+      positive_filter_ = UnitTestFilter{
+          positive_filter.size() ? positive_filter : kUniversalFilter};
+      negative_filter_ = UnitTestFilter{positive_and_negative_filters.back()};
+    } else {
+      // In case positive filter is empty
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:771]: Yeah, this is a mistake, will have to fix this one.

[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:771]: Yeah this is the case where negative filters is empty, this comment is not meant to be read on itself, it is part of a whole sentence including the next line, and it is explaining `positive_filter_ = UnitTestFilter{positive_filter};`. The formatter breaks the comment due to line length limitation.

File: googletest/src/gtest.cc [hunk 12]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
-    pattern = next_sep + 1;
   }
-  return true;
+
+  // Returns true if and only if test name (this is generated by appending test
+  // suit name and test name via a '.' character) matches the positive filter
+  // and does not match the negative filter.
+  bool MatchesTest(const std::string& test_suite_name,
+                   const std::string& test_name) const {
+    const std::string& full_name = test_suite_name + "." + test_name.c_str();
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:782]: Sure I'm using lines from old code I will update these as well.

File: googletest/src/gtest.cc (hunk 8 above)
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:766]: Sure this is the only behavior change this merge request contains, AFAIK. I will fix this, and hopefully the tests pass.

File: googletest/src/gtest.cc [hunk 13]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
+  // A filter is a list of patterns separated by ':'.
+  explicit PositiveAndNegativeUnitTestFilter(const std::string& filter) {
+    std::vector<std::string> positive_and_negative_filters;
+
+    SplitString(filter, '-', &positive_and_negative_filters);
+    const auto& positive_filter = positive_and_negative_filters.front();
+
+    if (positive_and_negative_filters.size() > 1) {
+      positive_filter_ = UnitTestFilter{
+          positive_filter.size() ? positive_filter : kUniversalFilter};
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:768]: Makes sense.

File: googletest/src/gtest.cc [hunk 14]
```diff
@@ -723,60 +723,92 @@ static bool PatternMatchesString(const std::string& name_str,
...
-      return true;
-    }
+namespace {
+class UnitTestFilter {
+ public:
+  UnitTestFilter() = default;
+
+  // Constructs a filter form a string of patterns separated by `:`.
+  explicit UnitTestFilter(const std::string& filter) {
+    if (filter.empty()) return;
```
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc:733]: You are correct this is an other behavior change.

File: googletest/src/gtest.cc (hunk 11 above)
[the remark this answers is not in the document]
Comment (IYP-Programer-Yeah) [reply googletest/src/gtest.cc]: Improved the comment.

**Comment by IYP-Programer-Yeah** [comment]
@dinord Requested changes are applied, and the newly added tests pass. I want your confirmation on the last open discussion.

**Comment by IYP-Programer-Yeah** [comment]
@dinord Any other issues to be concerned about?

**Comment by IYP-Programer-Yeah** [comment]
Happy new year, any hopes of getting this merged this year :D

File: googletest/src/gtest.cc [hunk 15]
```diff
@@ -723,60 +723,99 @@ static bool PatternMatchesString(const std::string& name_str,
...
-    if (PatternMatchesString(name_str, pattern, pattern_end)) {
-      return true;
-    }
+namespace {
+
+class UnitTestFilter {
+ public:
+  UnitTestFilter() = default;
+
+  // Constructs a filter form a string of patterns separated by `:`.
```
Comment (joshiayush) [inline googletest/src/gtest.cc:732]: I guess it's a typo, should be `from` not `form`.

**Review by joshiayush — CHANGES_REQUESTED** [review]

**Comment by IYP-Programer-Yeah** [comment]
@dinord Should I continue pinging this? or there is no hopes of getting this merged? Are there more internal errors?

**Comment by joshiayush** [comment]
> @dinord Should I continue pinging this? or there are no hopes of getting this merged? Are there more internal errors?

@IYP-Programer-Yeah There's no activity in this repository for the last 14 days, not only your PR is unmerged but there are other PRs as well, likely because the engineers are not able to devote time here but it's been 2 weeks so there are chances that they will be coming here soon :). You have to be patient :).

**Comment by dinord** [comment]
Thanks for addressing all the comments. I've started the import process once again. Hopefully we'll get this PR merged early next week.
