### PR TITLE
Fix MOCK_METHOD to handle noexcept correctly

### LINKED ISSUE #2472: GMock doesn't support noexcept functions
Hi, 

What is the current plan for supporting mocking `noexcept` functions? From searching StackOverflow, I understand that it's currently not possible to mock `noexcept` functions. Is there a workaround? 

Thanks

### PR DESCRIPTION
**Pull request by thejcannon**
Godbolt link to the preprocessed output of using the macro:
https://godbolt.org/z/rptA9J
(Scroll down to the bottom of the preprocessed output to see it parrotting the `noexcept` specifier verbatim)

Fixes #2472 

Let me know if y'all can think of any other test cases to throw at it.

### CODE REVIEW

File: googlemock/test/gmock-function-mocker_test.cc [hunk 1]
```diff
@@ -656,5 +657,27 @@ TEST(MockMethodMockFunctionTest, MockMethodSizeOverhead) {
...
+  MOCK_METHOD(void, func3, (), (noexcept(false)));
+  MOCK_METHOD(void, func4, (), (noexcept(noexcept(1+1))));
+  MOCK_METHOD(void, func5, (), (const, noexcept(noexcept(1+1))));
+  MOCK_METHOD(void, func6, (), (noexcept(noexcept(1+1)), const));
+  // Put commas in the noexcept expression
+  MOCK_METHOD(void, func7, (), (noexcept(noexcept(hasTwoParams(1,2))), const));
+};
+
+TEST(MockMethodMockFunctionTest, NoexceptSpecifierPreserved) {
+  EXPECT_TRUE(noexcept(std::declval<MockMethodNoexceptSpecifier>().func1()));
```
Comment (ugoren) [inline googlemock/test/gmock-function-mocker_test.cc]: Is there a reason to use declval here? I'd simply define a MockMethodNoexceptSpecifier object.
In case the compiler warns that it's unused, it can be suppressed by cast to void.

File: googlemock/test/gmock-function-mocker_test.cc [hunk 2]
```diff
@@ -656,5 +657,27 @@ TEST(MockMethodMockFunctionTest, MockMethodSizeOverhead) {
...
+  EXPECT_TRUE(noexcept(std::declval<MockMethodNoexceptSpecifier>().func2()));
+  EXPECT_FALSE(noexcept(std::declval<MockMethodNoexceptSpecifier>().func3()));
+  EXPECT_EQ(noexcept(std::declval<MockMethodNoexceptSpecifier>().func4()), noexcept(1+1));
+  EXPECT_EQ(noexcept(std::declval<MockMethodNoexceptSpecifier>().func5()), noexcept(1+1));
+  EXPECT_EQ(noexcept(std::declval<MockMethodNoexceptSpecifier>().func6()), noexcept(1+1));
+  EXPECT_EQ(noexcept(std::declval<MockMethodNoexceptSpecifier>().func7()), noexcept(hasTwoParams(1,2)));
+}
```
Comment (ugoren) [inline googlemock/test/gmock-function-mocker_test.cc]: I see no point in comparing with `noexcept(1+1)` - it simply evaluates to true. I suggest:

```
void Throws();
void DoesntThrow() noexcept;
struct MockMethodNoexceptSpecifier {
  MOCK_METHOD(void, func4, (), (noexcept(Throws())));
  MOCK_METHOD(void, func5, (), (noexcept(DoesntThrow())));
};
TEST(...) {
  EXPECT_FALSE(noexcept(mock.func4()));
  EXPECT_TRUE(noexcept(mock.func5()));
}
```

File: googlemock/test/gmock-function-mocker_test.cc (hunk 1 above)
Comment (thejcannon) [reply googlemock/test/gmock-function-mocker_test.cc]: I had that previously, but the compiler would always say the result of the expression is `noexcept(false)`.
https://travis-ci.org/google/googletest/jobs/594800623#L2313
My guess would be it has to do with the constructor not being marked `noexcept`.
But `declval` really is the "correct" solution as we just want to test the `noexcept` specifier for the function (and not the default constructor as well).

Another solution would be to use `std::is_nothrow_invocable`, but I don't think there's a technical reason to prefer one over another.

**Comment by thejcannon** [comment]
> Another small issue is behavior in case noexcept is used multiple times (which is invalid usage). I think it will lead to cryptic error messages, and better validation would be nice. But it isn't critical.

Seemingly it currently (before my change) leads to no error messages: https://godbolt.org/z/0TtYoG
So, some would argue that _any_ error message is better than none. I'll swing back around and work on a follow-up PR that makes the error message nice. It should be easy.

**Comment by gennadiycivil** [comment]
@thejcannon I am going to import this into internal system so we can have an internal review.
273951497
Thank you, we have started internal review. Please don't push any more changes into this PR as they might be overwritten.

File: googlemock/test/gmock-function-mocker_test.cc (hunk 1 above)
Comment (ugoren) [reply googlemock/test/gmock-function-mocker_test.cc]: My intention was to define one MockMethodNoexceptSpecifier object in the test, and use it in all expectations. Then it wouldn't matter if the constructor is noexcept.

Comment (thejcannon) [reply googlemock/test/gmock-function-mocker_test.cc]: That's definitely another solution. Personally, I wouldn't like having to declare an instance of an object (which is a runtime construct) just so syntactically (since `noexcept` expressions are evaluated at compile-time) I can reason about the methods. 
But I also can't argue it would be less code.
If this comes up in the "internal review" I'd be alright changing it.

**Comment by gennadiycivil** [comment]
@thejcannon Looks like this broke Windows builds.
See https://ci.appveyor.com/project/GoogleTestAppVeyor/googletest/builds/28041555

**Comment by thejcannon** [comment]
@gennadiycivil 
So the good news is that the bug was there before my change: https://godbolt.org/z/WbouCI
Looks like my tests just exposed them.

I'll take a look at it when I get to work today.

Might be related to #2490

**Comment by thejcannon** [comment]
#2514 has been created to fix the issue.

File: googlemock/test/gmock-function-mocker_test.cc (hunk 1 above)
Comment (thejcannon) [reply googlemock/test/gmock-function-mocker_test.cc]: Yeah, it's all about tradeoffs if you want to use `static_assert`s in your test code to test some logic. 
If you move it into a compile-time check, you know it'll always be true. The tests wouldn't compile otherwise. On the other hand, normally one test failing doesn't bar other tests from running and reporting their successes/failures. Since the `noexcept` spec wouldn't be absolutely fatal if it was wrong, I opted to implement them as runtime checks so they can report successes/failures just like other tests.
